export { distanceMetres } from './distance'
export type { Coordinate } from './distance'
export { nearestPlace } from './nearest'
export type { NamedPlace } from './nearest'
export { isProbableDuplicate, DUPLICATE_THRESHOLD_M } from './duplicate'
export { gradeAccuracy, GRADE_THRESHOLDS } from './classify'
export type { Reading, FixGrade } from './classify'
export { averageReadings } from './average'
export { holdVerdict } from './trend'
export type { HoldVerdict } from './trend'
